// DriftLens - GitHub PR creator via Octokit

import { Octokit } from '@octokit/rest';
import simpleGit from 'simple-git';
import type { PatternRecord, SkillTarget, DriftLensConfig } from '../shared/schema.js';
import { resolveApiKey } from '../shared/config.js';

export async function openGithubPR(
  pattern: PatternRecord,
  target: SkillTarget,
  config: DriftLensConfig,
  cwd: string
): Promise<string> {
  const token = resolveApiKey(config.git.token);
  const octokit = new Octokit({ auth: token });

  const git = simpleGit(cwd);
  const remoteUrl = await git.remote(['get-url', 'origin']);
  const [owner, repo] = parseGitHubRemote(remoteUrl?.trim() ?? '');

  const effectiveOwner = config.git.owner ?? owner;
  const effectiveRepo = config.git.repo ?? repo;

  if (!effectiveOwner || !effectiveRepo) {
    throw new Error('Could not determine GitHub owner/repo. Set git.owner and git.repo in config.');
  }

  const date = new Date().toISOString().split('T')[0] ?? 'unknown';
  const branch = `driftlens/skill-update-${pattern.name}-${date}`;

  // Create branch from HEAD
  await git.checkoutBranch(branch, 'HEAD');

  // Stage and commit the skill file change
  await git.add(target.path);
  await git.commit(`chore(skills): add ${pattern.name} rule\n\nAdded by DriftLens based on ${pattern.occurrences} corrections.`);

  // Push branch
  await git.push('origin', branch, ['--set-upstream']);

  // Revert to previous branch
  await git.checkout('-');

  // Build PR body
  const prBody = buildPRBody(pattern);

  const { data: pr } = await octokit.pulls.create({
    owner: effectiveOwner,
    repo: effectiveRepo,
    title: `chore(skills): add ${pattern.name} rule [DriftLens]`,
    body: prBody,
    head: branch,
    base: 'main',
    draft: true,
  });

  // Add label
  try {
    await octokit.issues.addLabels({
      owner: effectiveOwner,
      repo: effectiveRepo,
      issue_number: pr.number,
      labels: ['driftlens-proposal'],
    });
  } catch {
    // Label may not exist - ignore
  }

  return pr.html_url;
}

function parseGitHubRemote(url: string): [string, string] {
  // HTTPS: https://github.com/owner/repo.git
  // SSH: git@github.com:owner/repo.git
  const https = /github\.com\/([^/]+)\/([^/]+?)(?:\.git)?$/.exec(url);
  if (https) return [https[1] ?? '', https[2] ?? ''];
  const ssh = /github\.com:([^/]+)\/([^/]+?)(?:\.git)?$/.exec(url);
  if (ssh) return [ssh[1] ?? '', ssh[2] ?? ''];
  return ['', ''];
}

function buildPRBody(pattern: PatternRecord): string {
  const weeks = Math.max(
    1,
    Math.round(
      (new Date(pattern.last_seen).getTime() - new Date(pattern.first_seen).getTime()) /
        (7 * 86400000)
    )
  );

  return `## DriftLens Skill Proposal

**Pattern:** \`${pattern.name}\`

**Description:** ${pattern.description}

### Evidence

| Metric | Value |
|---|---|
| Corrections | ${pattern.occurrences} |
| Timespan | ~${weeks} week(s) |
| Confidence | ${(pattern.confidence * 100).toFixed(0)}% |
${pattern.avg_friction_score !== null ? `| Avg friction | ${pattern.avg_friction_score.toFixed(1)} turns |` : ''}

### Proposed Rule

${pattern.proposed_rule}

${
  pattern.example_before || pattern.example_after
    ? `### Example\n\n❌ Before:\n\`\`\`\n${pattern.example_before}\n\`\`\`\n\n✅ After:\n\`\`\`\n${pattern.example_after}\n\`\`\``
    : ''
}

---
*Generated by [DriftLens](https://github.com/driftlens/driftlens). Review and merge to improve your AI agent's skill file.*
`;
}
